  name: Bug Report
  description: Report a bug in Enhancements for Garmin Connect
  labels:
      - bug
  body:
    - type: textarea
      id: description
      attributes:
        label: Description
        placeholder: |
            Provide a general description of the bug
      validations:
        required: true
    - type: textarea
      id: reproduction
      attributes:
        label: Reproduction steps
        placeholder: |
            1. 
            2. 
            3.
            ...
      validations:
          required: true
    - type: dropdown
      id: platform
      attributes:
          label: Which platform did you discover this bug?
          options:
              - UserScript (Violentmonkey, Tampermonkey, etc)
              - Chrome Web Store
              - Firefox Add-ons
      validations:
          required: true
    - type: textarea
      id: environment
      attributes:
          label: Please provide the environment you discovered this bug
          render: true
          placeholder: |
              Version: 1.0.0
              Browser: Chrome 123.0.6312
              OS: macOS 14.3
    - type: textarea
      id: other
      attributes:
        label: Additional information