name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn install
      - run: yarn run prod
      - run: zip -r dist/browser/browser.zip dist/browser/*
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/browser/browser.zip
            dist/userscript/garmin-connect-enhancements.user.js
