name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **.ts
            **.js
      - name: Has changed files
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No changed files found, aborting action"
      - name: Setup node ${{ matrix.node-version }}
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
        if: steps.changed-files.outputs.any_changed == 'true'
      - run: yarn install
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Run ESLint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn eslint ${{ steps.changed-files.outputs.all_changed_files }}
