name: Release

on:
  workflow_dispatch:
    if: github.ref_name == github.event.repository.default_branch
    inputs:
      version:
        description: The version to publish (i.e. "v1.2.3").
        type: string
        required: true
      prerelease:
        description: Is this version a prerelease?
        type: boolean
        default: 'false'
        required: true

permissions:
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          allow_forks: false
      - name: Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
        with:
          tag_name: ${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}
          token: ${{ secrets.PAT }}
          fail_on_unmatched_files: true
          files: |
            dist/browser/garmin-connect-enhancements.unpackaged.chrome.zip
            dist/browser/garmin-connect-enhancements.unpackaged.gecko.zip
            dist/userscript/garmin-connect-enhancements.user.js
